name: GrumPHP

on: [push, pull_request]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest, windows-latest]
                php-versions: ['7.4']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
              #env:
              #  phpts: ts # Windows can handle TS or NTS - both dont work
            - name: Check Versions
              run: |
                php -v
                php -i
                php -m
            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-suggest
            - name: Try it
              run: php test.php
